-- v0.5.0 — SMS threads
--
-- Two-table model: one row per (tenant, contact_phone) thread, plus one row
-- per individual message. The existing `sms_sessions` table from the
-- WF5/AI-chatbot era is left in place but no longer used.
--
-- Idempotency: sms_messages.twilio_message_sid is UNIQUE so retries from
-- Twilio (which retries on any non-2xx response) don't create duplicates.

BEGIN;

-- ---------------------------------------------------------------------------
-- sms_threads
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sms_threads (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id       bigint NOT NULL REFERENCES "Clients"(id) ON DELETE CASCADE,
  contact_id      bigint REFERENCES contacts(id) ON DELETE SET NULL,

  -- Twilio number the contact texted (i.e. the tenant's number)
  tenant_phone    text NOT NULL,
  -- Contact's E.164 phone
  contact_phone   text NOT NULL,
  -- Display name. Pulled from contacts.name when contact_id is set, or null.
  -- Denormalized so the threads list doesn't need a join just to render.
  display_name    text,

  consent_status  text NOT NULL DEFAULT 'active'
    CHECK (consent_status IN ('active', 'stopped', 'help_sent')),

  -- Activity timestamps maintained by the inbound webhook + outbound API
  last_inbound_at  timestamptz,
  last_outbound_at timestamptz,
  last_message_at  timestamptz,
  last_message_preview text,
  last_read_at    timestamptz,

  -- Soft delete (matches jobs pattern)
  archived_at     timestamptz,

  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  -- One thread per (tenant, contact) pair. The tenant_phone is included so
  -- a tenant who later adds a second Twilio number gets a separate thread.
  UNIQUE (client_id, tenant_phone, contact_phone)
);

CREATE INDEX IF NOT EXISTS idx_sms_threads_client_lastmsg
  ON sms_threads (client_id, last_message_at DESC NULLS LAST)
  WHERE archived_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_sms_threads_contact
  ON sms_threads (contact_id)
  WHERE contact_id IS NOT NULL;

COMMENT ON TABLE sms_threads IS
  'One row per (tenant, contact_phone) SMS conversation. Holds aggregated metadata (last activity, consent state, unread cursor). Individual messages live in sms_messages.';

COMMENT ON COLUMN sms_threads.consent_status IS
  'active = can send. stopped = user texted STOP, do not send. help_sent = HELP keyword auto-replied this session.';

COMMENT ON COLUMN sms_threads.last_read_at IS
  'Timestamp of when the dashboard user last opened/read this thread. Unread = last_inbound_at > last_read_at.';

-- ---------------------------------------------------------------------------
-- sms_messages
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sms_messages (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id         bigint NOT NULL REFERENCES sms_threads(id) ON DELETE CASCADE,
  client_id         bigint NOT NULL REFERENCES "Clients"(id) ON DELETE CASCADE,

  direction         text NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  body              text NOT NULL,

  -- Twilio's MessageSid. Inbound: from the webhook. Outbound: from the API
  -- response. Unique to prevent dupes when Twilio retries inbound delivery.
  twilio_message_sid text UNIQUE,

  -- Twilio status: 'received' for inbound, plus 'queued'|'sending'|'sent'|
  -- 'delivered'|'undelivered'|'failed' for outbound (updated via status webhook
  -- in a future ship; we just store the latest).
  twilio_status     text,
  error_code        text,

  -- For outbound: which dashboard user clicked Send. Null for system/template.
  sent_by_user_id   uuid REFERENCES auth.users(id) ON DELETE SET NULL,

  -- For outbound: optional template that originated this message.
  -- (Templates table comes in v0.5.3; column reserved now to avoid migration churn.)
  template_key      text,

  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sms_messages_thread_created
  ON sms_messages (thread_id, created_at DESC);

COMMENT ON TABLE sms_messages IS
  'Individual SMS messages. Inbound rows come from the Twilio webhook; outbound rows come from the dashboard reply box. twilio_message_sid is UNIQUE for idempotent retries.';

-- ---------------------------------------------------------------------------
-- Trigger: keep sms_threads.last_* in sync when a message is inserted.
-- This avoids the application code having to do a follow-up UPDATE.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION sms_threads_update_on_message()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.direction = 'inbound' THEN
    UPDATE sms_threads
    SET last_inbound_at = NEW.created_at,
        last_message_at = NEW.created_at,
        last_message_preview = LEFT(NEW.body, 200),
        updated_at = now()
    WHERE id = NEW.thread_id;
  ELSE
    UPDATE sms_threads
    SET last_outbound_at = NEW.created_at,
        last_message_at = NEW.created_at,
        last_message_preview = LEFT(NEW.body, 200),
        updated_at = now()
    WHERE id = NEW.thread_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sms_messages_update_thread ON sms_messages;
CREATE TRIGGER sms_messages_update_thread
  AFTER INSERT ON sms_messages
  FOR EACH ROW
  EXECUTE FUNCTION sms_threads_update_on_message();

-- ---------------------------------------------------------------------------
-- Notifications kind: add sms_received
-- ---------------------------------------------------------------------------
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_kind_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_kind_check
  CHECK (kind = ANY (ARRAY[
    'estimate_saved'::text,
    'booking_saved'::text,
    'booking_rescheduled'::text,
    'booking_cancelled'::text,
    'message_left'::text,
    'invoice_paid'::text,
    'callback_received'::text,
    'sms_received'::text
  ]));

-- ---------------------------------------------------------------------------
-- RLS — match the rest of the app
-- ---------------------------------------------------------------------------
ALTER TABLE sms_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE sms_messages ENABLE ROW LEVEL SECURITY;

-- Reuses public.current_user_client_ids() helper from the earlier migration
-- to avoid the recursion problem with client_users self-referencing.
DROP POLICY IF EXISTS sms_threads_select ON sms_threads;
CREATE POLICY sms_threads_select ON sms_threads
  FOR SELECT
  USING (client_id = ANY (public.current_user_client_ids()));

DROP POLICY IF EXISTS sms_threads_update ON sms_threads;
CREATE POLICY sms_threads_update ON sms_threads
  FOR UPDATE
  USING (client_id = ANY (public.current_user_client_ids()));

DROP POLICY IF EXISTS sms_messages_select ON sms_messages;
CREATE POLICY sms_messages_select ON sms_messages
  FOR SELECT
  USING (client_id = ANY (public.current_user_client_ids()));

-- Server-side inserts (webhook + outbound API) use the service role key
-- which bypasses RLS, so no INSERT policy needed for app users.

COMMIT;
